/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static pacote.conexao.con;


/**
 *
 * @author c02maq1
 */
public class alterar extends javax.swing.JFrame {
    loginaccount lga = new loginaccount();

    /**
     * Creates new form cadastro
     */
    public alterar() {
        initComponents();
        
        
        String id = lga.id;
        Ccmpnome.setText(lga.nome);
        Ccmplogin.setText(lga.login);
        Ccmpsenha.setText(lga.senha);
    }
    
    public static void substituir() {
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limitador1 = new javax.swing.JLabel();
        limitador2 = new javax.swing.JLabel();
        limitador3 = new javax.swing.JLabel();
        limitador4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ccmpnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ccmplogin = new javax.swing.JTextField();
        Ccmpsenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btncadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnexcluir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(480, 200, 500, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(limitador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 10));
        getContentPane().add(limitador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 10));
        getContentPane().add(limitador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 30, 10));
        getContentPane().add(limitador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 10, 10));

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Altere seus dados da maneira que desejar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));
        getContentPane().add(Ccmpnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));
        getContentPane().add(Ccmplogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 340, -1));
        getContentPane().add(Ccmpsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Senha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        btncadastrar.setBackground(new java.awt.Color(153, 153, 153));
        btncadastrar.setText("Alterar dados");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, -1));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, -1));

        btnexcluir.setText("Excluir conta");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        janelas.menu.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        String sql,id= lga.id,novonome,novologin,novasenha;
        if ((Ccmpnome.getText().equals(lga.nome)) && (Ccmplogin.getText().equals(lga.login)) && (Ccmpsenha.getText().equals(lga.senha))){
            System.out.println("As novas informações não devem ser exatamente iguais às anteriores.");
        } else {
        sql = "update usuarios set nome =?, login = ?, senha = ? where id = ?";
        try {
            PreparedStatement stm  = con.prepareStatement(sql);
            stm.setString(1,novonome = Ccmpnome.getText());
            stm.setString(2, novologin = Ccmplogin.getText());
            stm.setString(3, novasenha  =  Ccmpsenha.getText());
            stm.setString(4,id);
            stm.execute();
            JOptionPane.showMessageDialog(this,"Dados alterados!");
            lga.nome = novonome;
            lga.login = novologin;
            lga.senha = novasenha;
            
        } catch (SQLException e) {
            System.out.println("Não alterou");
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
 int apagar;
        apagar = JOptionPane.showConfirmDialog(null,"Deseja excluir permanentemente sua conta?","Apagando..",0);
        if (apagar == 0){
            String sql;
            sql = "delete from usuarios where id = ?";
            try {
                PreparedStatement stm  = con.prepareStatement(sql);
                stm.setString(1,lga.id);
                stm.execute();
                JOptionPane.showMessageDialog(this,"Conta excluida. Até breve.");
                janelas.logar.show();
                dispose();
            } catch (SQLException e) {
                System.out.println("Não apagou por erro");
                System.out.println(e);
            }

        } else {
            System.out.println("Escolheu não apagar");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ccmplogin;
    private javax.swing.JTextField Ccmpnome;
    private javax.swing.JTextField Ccmpsenha;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JToggleButton btnexcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel limitador1;
    private javax.swing.JLabel limitador2;
    private javax.swing.JLabel limitador3;
    private javax.swing.JLabel limitador4;
    // End of variables declaration//GEN-END:variables
}
