/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static pacote.conexao.con;
/**
 *
 * @author c02maq1
 */
public class inicio extends javax.swing.JFrame {
    loginaccount lga = new loginaccount();
    boolean encolhida=false;


    /**
     * Creates new form inicio
     */
    public inicio() {
       initComponents();
       janelas.logar.dispose();
       this.setLocationRelativeTo(null);
       
         
    }
  
    public void barra(){
    if (encolhida == false){
        //System.out.println("encolheu");
        barraferramenta.setSize(50,400);
        //Txtcentral.setVisible(false);
        Txtlinha.setVisible(false);
        encolhida = true;
    } else if (encolhida == true){
        //System.out.println("expandiu");
        barraferramenta.setSize(220,400);
        //Txtcentral.setVisible(true);
        Txtlinha.setVisible(true);
        encolhida = false;
    }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limitador2 = new javax.swing.JLabel();
        limitador3 = new javax.swing.JLabel();
        limitador4 = new javax.swing.JLabel();
        telafunc = new javax.swing.JPanel();
        menuinicial = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        barraferramenta = new javax.swing.JPanel();
        btndeslogar = new javax.swing.JButton();
        Txtlinha = new javax.swing.JLabel();
        Txtcentral = new javax.swing.JLabel();
        fundovenda = new javax.swing.JPanel();
        bntvenda = new javax.swing.JButton();
        fundohistorico = new javax.swing.JPanel();
        btnhist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do colaborador\n");
        setBounds(new java.awt.Rectangle(480, 200, 500, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(limitador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(limitador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 30, 10));
        getContentPane().add(limitador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 40, 10));

        telafunc.setBackground(new java.awt.Color(51, 103, 193));
        telafunc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuinicial.setBackground(new java.awt.Color(51, 103, 193));
        menuinicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/team (2).png"))); // NOI18N
        menuinicial.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 400, 250));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("</> Não altere aquilo que não compreende.");
        menuinicial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("</> Qualquer dúvida chame sua equipe de TI.");
        menuinicial.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("</> JAMAIS insira pen-drive's nesta máquina.");
        menuinicial.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Escolha a ferramente que deseja ao lado!");
        menuinicial.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lembre-se:");
        menuinicial.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 40));

        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        menuinicial.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 70));

        telafunc.add(menuinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        getContentPane().add(telafunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 400, 400));

        barraferramenta.setBackground(new java.awt.Color(45, 45, 45));
        barraferramenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraferramenta.setFocusable(false);
        barraferramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barraferramentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barraferramentaMouseExited(evt);
            }
        });
        barraferramenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndeslogar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndeslogar.setForeground(new java.awt.Color(255, 255, 255));
        btndeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/exit.png"))); // NOI18N
        btndeslogar.setText("Sair da aplicação");
        btndeslogar.setBorder(null);
        btndeslogar.setContentAreaFilled(false);
        btndeslogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndeslogar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btndeslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeslogarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeslogarMouseExited(evt);
            }
        });
        btndeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeslogarActionPerformed(evt);
            }
        });
        barraferramenta.add(btndeslogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, 40));

        Txtlinha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        barraferramenta.add(Txtlinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 200, -1));

        Txtcentral.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        Txtcentral.setForeground(new java.awt.Color(255, 255, 255));
        Txtcentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txtcentral.setText("Cental do Colaborador");
        barraferramenta.add(Txtcentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        fundovenda.setBackground(new java.awt.Color(45, 45, 45));
        fundovenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntvenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntvenda.setForeground(new java.awt.Color(255, 255, 255));
        bntvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/carrinho-de-compras.png"))); // NOI18N
        bntvenda.setText("Realize pedidos");
        bntvenda.setContentAreaFilled(false);
        bntvenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntvenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntvenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntvenda.setIconTextGap(15);
        bntvenda.setRolloverEnabled(false);
        bntvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntvendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntvendaMouseExited(evt);
            }
        });
        bntvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntvendaActionPerformed(evt);
            }
        });
        fundovenda.add(bntvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        barraferramenta.add(fundovenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 50));

        fundohistorico.setBackground(new java.awt.Color(45, 45, 45));
        fundohistorico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhist.setForeground(new java.awt.Color(255, 255, 255));
        btnhist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/historical.png"))); // NOI18N
        btnhist.setText("Consulte o histórico");
        btnhist.setContentAreaFilled(false);
        btnhist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnhist.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnhist.setIconTextGap(15);
        btnhist.setRolloverEnabled(false);
        btnhist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhistMouseExited(evt);
            }
        });
        btnhist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistActionPerformed(evt);
            }
        });
        fundohistorico.add(btnhist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        barraferramenta.add(fundohistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 50));

        getContentPane().add(barraferramenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeslogarActionPerformed
        int sair;
        sair = JOptionPane.showConfirmDialog(null,"Deseja deslogar?","Saindo",0);
        if (sair == 0){
            janelas.logar.show();
            dispose();
            lga.login = "";
            lga.senha = "";
            btndeslogar.setForeground(new java.awt.Color(51,153,255));
        } else {
            System.out.println("permaneceu");
        }
    }//GEN-LAST:event_btndeslogarActionPerformed

     // ====================================
    //            MUDA AS CORES
    //              AO PASSAR
    //               O MOUSE
    //             BTN DESLOGAR
    // ====================================
    private void btndeslogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeslogarMouseExited
        btndeslogar.setForeground(new java.awt.Color(51,117,255));
    }//GEN-LAST:event_btndeslogarMouseExited

    private void btndeslogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeslogarMouseEntered
        btndeslogar.setForeground(new java.awt.Color(51,153,255));
    }//GEN-LAST:event_btndeslogarMouseEntered

    private void bntvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntvendaActionPerformed
       janelas.venda.show();
        dispose();
    }//GEN-LAST:event_bntvendaActionPerformed
     // ====================================
    //            MUDA AS CORES
    //              AO PASSAR
    //               O MOUSE
    //             REALIZE VENDAS
    // ====================================
    private void bntvendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntvendaMouseEntered
        fundovenda.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_bntvendaMouseEntered

    private void bntvendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntvendaMouseExited
       fundovenda.setBackground(new java.awt.Color(45,45,45));
    }//GEN-LAST:event_bntvendaMouseExited
  // ====================================
    //            MUDA AS CORES
    //              AO PASSAR
    //               O MOUSE
    //             consulte historico
    // ====================================
    private void btnhistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistMouseEntered
        fundohistorico.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_btnhistMouseEntered

    private void btnhistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistMouseExited
         fundohistorico.setBackground(new java.awt.Color(45,45,45));
    }//GEN-LAST:event_btnhistMouseExited

    private void btnhistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhistActionPerformed
  // ====================================
    //            encolhe e expande
    //              AO PASSAR
    //               O MOUSE
    //             BARRA DE FERRAMENTA
    // ====================================
    private void barraferramentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraferramentaMouseEntered
        // System.out.println("entrou");
        // barra();
    }//GEN-LAST:event_barraferramentaMouseEntered

    private void barraferramentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraferramentaMouseExited
        // System.out.println("saiu");
        // barra();
    }//GEN-LAST:event_barraferramentaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Txtcentral;
    private javax.swing.JLabel Txtlinha;
    private javax.swing.JPanel barraferramenta;
    private javax.swing.JButton bntvenda;
    private javax.swing.JButton btndeslogar;
    private javax.swing.JButton btnhist;
    private javax.swing.JPanel fundohistorico;
    private javax.swing.JPanel fundovenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel limitador2;
    private javax.swing.JLabel limitador3;
    private javax.swing.JLabel limitador4;
    private javax.swing.JPanel menuinicial;
    private javax.swing.JPanel telafunc;
    // End of variables declaration//GEN-END:variables
}
