/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static pacote.conexao.con;


/**
 *
 * @author c02maq1
 */
public class tela extends javax.swing.JFrame {
    cadastro cadastrar = new cadastro();
    loginaccount lga = new loginaccount();
    /**
     * Creates new form tela
     */
    public tela() {
        
        initComponents();
        conexao.Conectar();
        this.setLocationRelativeTo(null);
        cmplogin.setBackground(new java.awt.Color(0,0,0,1));
        cmpsenha.setBackground(new java.awt.Color(0,0,0,1));
        btnLogin.setBackground(new java.awt.Color(227, 89, 114));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        formLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmplogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmpsenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entre na sua conta");
        setBackground(new java.awt.Color(153, 255, 0));
        setBounds(new java.awt.Rectangle(550, 250, 300, 400));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formLogin.setBackground(new java.awt.Color(51, 103, 193));
        formLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(72, 61, 139));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Login");
        jLabel2.setDoubleBuffered(true);
        jLabel2.setFocusable(false);
        formLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel1.setBackground(new java.awt.Color(72, 61, 139));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Senha");
        jLabel1.setFocusable(false);
        formLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        cmplogin.setBackground(new java.awt.Color(40, 40, 40));
        cmplogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmplogin.setAlignmentX(1.0F);
        cmplogin.setBorder(null);
        formLogin.add(cmplogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 170, 20));

        btnLogin.setBackground(new java.awt.Color(227, 89, 114));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("Entrar");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLogin.setFocusPainted(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        formLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 170, 30));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        formLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        formLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, -1));

        cmpsenha.setBackground(new java.awt.Color(40, 40, 40));
        cmpsenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cmpsenha.setBorder(null);
        formLogin.add(cmpsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 20));

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/man (1).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 0, 20, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Central do Colaborador");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 0, 230, 30);

        formLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        formLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, -1));

        getContentPane().add(formLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       lga.login = cmplogin.getText();
       lga.senha = cmpsenha.getText();
       cmplogin.setText("");
       cmpsenha.setText("");
       dispose();
       lga.loginacess();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField cmplogin;
    private javax.swing.JPasswordField cmpsenha;
    private javax.swing.JPanel formLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
