/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import static pacote.conexao.con;
import static pacote.loginaccount.login;

/**
 *
 * @author c02maq1
 */
public class vender extends javax.swing.JFrame {
    DefaultListModel carr = new DefaultListModel();
    int totalcarrinho, totalitens;
    String tempitem;
    /**
     * Creates new form vender
     */
    public vender() {
        initComponents();
        carrinho.setModel(carr);
        this.setLocationRelativeTo(null);
        
        
    }
    
    public void carrinho() {
        int unidade, valor,totalitem;
        
        unidade =  Integer.parseInt(cmpvenda.getText());
        valor = Integer.parseInt(cmpreco.getText());
        
        if (cmpdesconto != null){
            if (cmpdesc.getText() == tempitem){
                JOptionPane.showMessageDialog(this,"Venda implantada!"); 
            } else {
            totalitem = unidade * valor;
            totalcarrinho = totalcarrinho + totalitem;
            totalitens = totalitens + unidade;
            carr.addElement(cmpvenda.getText()+ " - " + cmpdesc.getText() + " - " + totalitem);
            txtotal.setText(String.valueOf(totalcarrinho));
            txtTitem.setText(String.valueOf(totalitens));
            }
        } else {
            JOptionPane.showMessageDialog(this,"Sistema de desconto não aplicável, por favor deixe o campo em branco"); 
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cmpnome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmpcpf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmptel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmpemail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmpcep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmpcod = new javax.swing.JTextField();
        cmpendereco = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        cmpcidade = new javax.swing.JTextField();
        cmpestado = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmpestoque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmpdesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmpitem = new javax.swing.JTextField();
        cmpreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmpvenda = new javax.swing.JTextField();
        cmpdesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carrinho = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        txtTitem = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(51, 103, 193));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Nome");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 50, 20));

        cmpnome.setEditable(false);
        cmpnome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpnome.setFocusable(false);
        cmpnome.setRequestFocusEnabled(false);
        jPanel3.add(cmpnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 30));

        jLabel13.setText("CPF");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 90, -1));

        cmpcpf.setEditable(false);
        cmpcpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpcpf.setFocusable(false);
        cmpcpf.setRequestFocusEnabled(false);
        jPanel3.add(cmpcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        jLabel14.setText("Telefone");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 10));

        cmptel.setEditable(false);
        cmptel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmptel.setFocusable(false);
        cmptel.setRequestFocusEnabled(false);
        jPanel3.add(cmptel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 30));

        jLabel15.setText("Email");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 10));

        cmpemail.setEditable(false);
        cmpemail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpemail.setFocusable(false);
        cmpemail.setRequestFocusEnabled(false);
        jPanel3.add(cmpemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 30));

        jLabel19.setText("CEP");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 50, 10));

        cmpcep.setEditable(false);
        cmpcep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpcep.setFocusable(false);
        cmpcep.setRequestFocusEnabled(false);
        jPanel3.add(cmpcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 70, 30));

        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, -1));

        jLabel2.setText("Código do cliente**");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 110, 30));

        cmpcod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmpcodFocusLost(evt);
            }
        });
        jPanel3.add(cmpcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        cmpendereco.setEditable(false);
        cmpendereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpendereco.setFocusable(false);
        cmpendereco.setRequestFocusEnabled(false);
        jPanel3.add(cmpendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 30));

        jLabel20.setText("Endereço");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, 20));

        Cidade.setText("Cidade");
        jPanel3.add(Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 134, 90, 20));

        cmpcidade.setEditable(false);
        cmpcidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpcidade.setFocusable(false);
        cmpcidade.setRequestFocusEnabled(false);
        jPanel3.add(cmpcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 30));

        cmpestado.setEditable(false);
        cmpestado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cmpestado.setFocusable(false);
        cmpestado.setRequestFocusEnabled(false);
        jPanel3.add(cmpestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 50, 30));

        jLabel21.setText("Sigla estado");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 70, 20));

        jTabbedPane2.addTab("Cliente", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Código de item");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        cmpestoque.setEditable(false);
        jPanel1.add(cmpestoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        jLabel4.setText("Descrição");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

        cmpdesc.setEditable(false);
        jPanel1.add(cmpdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, -1));

        jLabel5.setText("Carrinho do cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        cmpitem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmpitemFocusLost(evt);
            }
        });
        cmpitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpitemActionPerformed(evt);
            }
        });
        jPanel1.add(cmpitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        cmpreco.setEditable(false);
        jPanel1.add(cmpreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, -1));

        jLabel6.setText("Qnt. de venda");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel7.setText("Preço unitário");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, -1));
        jPanel1.add(cmpvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));
        jPanel1.add(cmpdesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabel8.setText("Desconto aplicado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jScrollPane1.setViewportView(carrinho);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 160, 100));

        jLabel9.setText("Qnt. em estoque");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        btnadd.setText("Adicionar");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, -1));
        jPanel1.add(txtTitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, 30));

        jLabel11.setText("Total Itens:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 30));

        jButton1.setText("Implantar venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel16.setText("Preço total:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 30));
        jPanel1.add(txtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, 30));

        jTabbedPane2.addTab("Itens", jPanel1);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmpcodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmpcodFocusLost
        String sql;
        sql = "select * from clientes where id = ?";
        try {
            PreparedStatement stm  = con.prepareStatement(sql);
            stm.setString(1,cmpcod.getText());

            ResultSet rs = stm.executeQuery();
            if (!rs.first()) {
                System.out.println("nao achou");
            } else {
                faturar.cliente = rs.getString("id");
                cmpnome.setText(rs.getString("nome"));
                cmpcpf.setText(rs.getString("cpf"));
                cmptel.setText(rs.getString("telefone"));
                cmpemail.setText(rs.getString("email"));
                cmpendereco.setText(rs.getString("endereco"));
                cmpcidade.setText(rs.getString("cidade"));
                cmpestado.setText(rs.getString("estado"));
                cmpcep.setText(rs.getString("cep"));
                
            }
        } catch (SQLException e) {
            System.out.println("Erro");
            System.out.println(e);
        }
    
    }//GEN-LAST:event_cmpcodFocusLost

    private void cmpitemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmpitemFocusLost
       String sql2;
        sql2 = "select * from estoque where itemid = ?";
        try {
            PreparedStatement stm  = con.prepareStatement(sql2);
            stm.setString(1,cmpitem.getText());

            ResultSet rs = stm.executeQuery();
            if (!rs.first()) {
                System.out.println("nao achou");
            } else {
                System.out.println("achou");
                cmpdesc.setText(rs.getString("descricao"));
                cmpestoque.setText(rs.getString("quantidade"));
                cmpreco.setText(rs.getString("preco"));
                
            }
        } catch (SQLException e) {
            System.out.println("Erro");
            System.out.println(e);
        }
    }//GEN-LAST:event_cmpitemFocusLost

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
         if (Integer.parseInt(cmpvenda.getText()) < Float.parseFloat(cmpestoque.getText())){
            carrinho();
            } else {
                System.out.println("erro de estoque");
            }

    }//GEN-LAST:event_btnaddActionPerformed

    private void cmpitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpitemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql;
        sql = "INSERT INTO `historico`( `usuario`, `totalpreco`, `data`, `totalitem`) VALUES (?,?,SYSDATE(),?)";
        try {
            PreparedStatement stm  = con.prepareStatement(sql);
            stm.setString(1,cmpnome.getText());
            stm.setString(2,String.valueOf(totalcarrinho));
            stm.setString(3,String.valueOf(totalitens));
            stm.execute();
            JOptionPane.showMessageDialog(this,"Venda implantada!");        
        } catch (SQLException e) {
            System.out.println("Não Implantou");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cidade;
    private javax.swing.JButton btnadd;
    private javax.swing.JList<String> carrinho;
    private javax.swing.JTextField cmpcep;
    private javax.swing.JTextField cmpcidade;
    private javax.swing.JTextField cmpcod;
    private javax.swing.JTextField cmpcpf;
    private javax.swing.JTextField cmpdesc;
    private javax.swing.JTextField cmpdesconto;
    private javax.swing.JTextField cmpemail;
    private javax.swing.JTextField cmpendereco;
    private javax.swing.JTextField cmpestado;
    private javax.swing.JTextField cmpestoque;
    private javax.swing.JTextField cmpitem;
    private javax.swing.JTextField cmpnome;
    private javax.swing.JTextField cmpreco;
    private javax.swing.JTextField cmptel;
    private javax.swing.JTextField cmpvenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel txtTitem;
    private javax.swing.JLabel txtotal;
    // End of variables declaration//GEN-END:variables
}
